version: '3.5'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # PGDATA: ./data/postgres
    ports:
      - "6432:5432"
    restart: unless-stopped
